-- Run this in Supabase Dashboard → SQL Editor (once).

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  designation text not null,
  degrees text[] not null default '{}',
  department text not null,
  experience text not null default 'Not specified',
  visiting_days text[] not null default '{}',
  timings text not null default 'By appointment',
  expertise text[] not null default '{}',
  biography text not null default '',
  image text not null default '/logo.jpeg',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists doctors_department_idx on public.doctors (department);
create index if not exists doctors_slug_idx on public.doctors (slug);

alter table public.doctors enable row level security;

drop policy if exists "Public can read doctors" on public.doctors;
create policy "Public can read doctors"
  on public.doctors
  for select
  to anon, authenticated
  using (true);

-- Writes happen only via the secret key (bypasses RLS) from Next.js API routes.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'doctor-images',
  'doctor-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read doctor images" on storage.objects;
create policy "Public can read doctor images"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'doctor-images');
